import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import {
  ArrowLeft,
  CheckCircle2,
  Copy,
  Circle,
  ExternalLink,
  Send,
} from "lucide-react";
import { useAppStore } from "@/store/useAppStore";
import { PageHeader, SectionCard, Badge, EmptyState } from "@/components/ui";
import { toast } from "@/components/Toast";
import { copyText, formatRelative } from "@/lib/util";
import {
  FORMAT_IDS,
  FORMAT_LABELS,
  format,
  type FormatId,
} from "@/lib/formatters";
import type { ContentItem, ContentKind } from "@/types";

/**
 * Publishing Workspace.
 *
 * A focused per-campaign view that takes the assets generated by the
 * Campaign Builder (or attached manually) and helps the user prepare them
 * for publication. Three jobs:
 *   1. Show each asset formatted the way the target platform wants it
 *      (plain text by default, with Markdown/HTML toggles per asset).
 *   2. One-click copy of the formatted text.
 *   3. Track publishing status per asset so the user can see "X of N
 *      published" progress on a campaign without integrating with any
 *      platform's API.
 *
 * This module deliberately does NOT:
 *   - Publish to platforms directly (out of scope; would require backend).
 *   - Modify the assets it displays (edits still happen in the Content
 *     Library or Campaign Builder).
 *   - Schedule publishing — there's no calendar here.
 */
export default function PublishingWorkspacePage() {
  const { id = "" } = useParams();
  const campaign = useAppStore((s) => s.campaigns.find((c) => c.id === id));
  const content = useAppStore((s) => s.content);
  const updateContent = useAppStore((s) => s.updateContent);

  const assets = useMemo(
    () => content.filter((c) => c.campaignId === id),
    [content, id]
  );

  if (!campaign) {
    return (
      <EmptyState
        title="Campaign not found"
        hint="It may have been deleted."
        action={
          <Link to="/campaigns" className="btn-secondary mt-3">
            <ArrowLeft className="h-4 w-4" /> Back to campaigns
          </Link>
        }
      />
    );
  }

  const total = assets.length;
  const published = assets.filter((a) => !!a.publishedAt).length;
  const progress = total > 0 ? published / total : 0;

  const grouped = useMemo(() => groupByKind(assets), [assets]);

  async function markPublished(asset: ContentItem, on: boolean) {
    await updateContent(asset.id, {
      publishedAt: on ? Date.now() : undefined,
    });
    toast.success(on ? "Marked as published" : "Marked as unpublished");
  }

  async function bulkMark(kind: ContentKind, on: boolean) {
    const items = grouped.get(kind) ?? [];
    await Promise.all(
      items.map((a) =>
        updateContent(a.id, { publishedAt: on ? Date.now() : undefined })
      )
    );
    toast.success(
      `${items.length} asset${items.length === 1 ? "" : "s"} ${
        on ? "marked published" : "unmarked"
      }`
    );
  }

  return (
    <>
      <PageHeader
        title={
          <span className="flex items-center gap-2">
            <Send className="h-6 w-6 text-brand-500" /> Publishing Workspace
          </span>
        }
        description={campaign.name}
      >
        <Link to={`/campaigns/${campaign.id}`} className="btn-secondary">
          <ArrowLeft className="h-4 w-4" /> Back to campaign
        </Link>
      </PageHeader>

      {/* Progress */}
      <SectionCard title="Publishing progress" className="mb-5">
        <div className="mb-2 flex items-center justify-between text-xs text-slate-500">
          <span>
            <strong>{published}</strong> / {total} asset
            {total === 1 ? "" : "s"} marked published
          </span>
          <span>{total === 0 ? "—" : `${Math.round(progress * 100)}%`}</span>
        </div>
        <div className="h-2 w-full overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800">
          <div
            className="h-full bg-gradient-to-r from-brand-500 to-pink-500 transition-all"
            style={{ width: `${progress * 100}%` }}
          />
        </div>
        <p className="mt-3 text-[11px] text-slate-500">
          Marking an asset as published is a local-only checkbox — it records
          that you copied this content out to its target platform. The
          platform itself isn't notified.
        </p>
      </SectionCard>

      {/* Assets grouped by kind */}
      {assets.length === 0 ? (
        <EmptyState
          title="No assets to publish"
          hint="Run the Campaign Builder on this campaign or attach existing content from the Campaign Detail page."
          action={
            <Link
              to={`/builder?product=${campaign.productIds[0] ?? ""}`}
              className="btn-primary mt-3"
            >
              Open Campaign Builder
            </Link>
          }
        />
      ) : (
        KIND_ORDER.filter((k) => grouped.has(k)).map((kind) => (
          <SectionCard
            key={kind}
            title={
              <span className="flex items-center gap-2">
                {KIND_LABEL[kind]}
                <span className="chip text-[10px]">
                  {grouped.get(kind)!.length}
                </span>
              </span>
            }
            className="mb-5"
            action={
              <div className="flex gap-1">
                <button
                  className="btn-ghost text-xs"
                  onClick={() => bulkMark(kind, true)}
                  title="Mark all in this section as published"
                >
                  <CheckCircle2 className="h-3 w-3" /> Mark all
                </button>
                <button
                  className="btn-ghost text-xs"
                  onClick={() => bulkMark(kind, false)}
                  title="Unmark all in this section"
                >
                  <Circle className="h-3 w-3" /> Unmark all
                </button>
              </div>
            }
          >
            <div className="space-y-4">
              {grouped.get(kind)!.map((a) => (
                <AssetCard
                  key={a.id}
                  asset={a}
                  onTogglePublished={(on) => markPublished(a, on)}
                />
              ))}
            </div>
          </SectionCard>
        ))
      )}
    </>
  );
}

/* ---------- AssetCard ---------- */

function AssetCard({
  asset,
  onTogglePublished,
}: {
  asset: ContentItem;
  onTogglePublished: (on: boolean) => void;
}) {
  // Default to plain text — that's what most target platforms (Pinterest,
  // ConvertKit, Facebook, Instagram, X) actually want when pasted from
  // the clipboard. The user can flip to Markdown or HTML per asset.
  const [fmt, setFmt] = useState<FormatId>("plain");
  const rendered = useMemo(() => format(asset.body, fmt), [asset.body, fmt]);
  const isPublished = !!asset.publishedAt;

  async function onCopy() {
    const ok = await copyText(rendered);
    if (ok) toast.success("Copied to clipboard");
    else toast.error("Copy failed");
  }

  return (
    <div
      className={`rounded-lg border p-3 transition ${
        isPublished
          ? "border-emerald-200 bg-emerald-50/40 dark:border-emerald-900 dark:bg-emerald-950/20"
          : "border-slate-200 dark:border-slate-700"
      }`}
    >
      <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-2 text-sm font-medium">
          {isPublished ? (
            <CheckCircle2 className="h-4 w-4 text-emerald-500" />
          ) : (
            <Circle className="h-4 w-4 text-slate-300 dark:text-slate-600" />
          )}
          <span>{asset.title}</span>
          {isPublished && asset.publishedAt && (
            <span className="text-[11px] text-slate-500">
              · published {formatRelative(asset.publishedAt)}
            </span>
          )}
        </div>
        <div className="flex items-center gap-1">
          <FormatToggle value={fmt} onChange={setFmt} />
          <button
            className="btn-secondary h-7"
            onClick={onCopy}
            title="Copy formatted output"
          >
            <Copy className="h-3.5 w-3.5" /> Copy
          </button>
          <button
            className={
              isPublished
                ? "btn-ghost h-7 text-xs"
                : "btn-primary h-7 text-xs"
            }
            onClick={() => onTogglePublished(!isPublished)}
          >
            {isPublished ? (
              <>
                <Circle className="h-3 w-3" /> Unmark
              </>
            ) : (
              <>
                <CheckCircle2 className="h-3 w-3" /> Mark published
              </>
            )}
          </button>
          <Link
            to={`/library?focus=${asset.id}`}
            className="btn-ghost h-7 text-xs"
            title="Open in Content Library to edit"
          >
            <ExternalLink className="h-3 w-3" />
          </Link>
        </div>
      </div>
      <div className="mb-1 flex items-center gap-2 text-[11px] text-slate-500">
        <Badge tone="info">{asset.kind}</Badge>
        <span>{FORMAT_LABELS[fmt]} preview · read-only here</span>
      </div>
      {fmt === "html" ? (
        // Always show source for HTML — pasted HTML is the user's actual
        // payload for blogs / Payhip, not the rendered preview.
        <pre className="max-h-80 overflow-auto rounded-md border border-slate-200 bg-white p-2.5 font-mono text-[11px] leading-relaxed text-slate-800 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100">
          {rendered}
        </pre>
      ) : (
        <pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-md border border-slate-200 bg-white p-2.5 font-mono text-[12px] leading-relaxed text-slate-800 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100">
          {rendered}
        </pre>
      )}
    </div>
  );
}

/* ---------- FormatToggle ---------- */

function FormatToggle({
  value,
  onChange,
}: {
  value: FormatId;
  onChange: (v: FormatId) => void;
}) {
  return (
    <div
      role="group"
      aria-label="Output format"
      className="inline-flex overflow-hidden rounded-md border border-slate-200 dark:border-slate-700"
    >
      {FORMAT_IDS.map((id) => (
        <button
          key={id}
          type="button"
          aria-pressed={value === id}
          onClick={() => onChange(id)}
          className={`px-2 py-1 text-[11px] font-medium transition-colors ${
            value === id
              ? "bg-brand-600 text-white"
              : "bg-white text-slate-600 hover:bg-slate-50 dark:bg-slate-900 dark:text-slate-300 dark:hover:bg-slate-800"
          }`}
        >
          {FORMAT_LABELS[id]}
        </button>
      ))}
    </div>
  );
}

/* ---------- helpers ---------- */

const KIND_ORDER: ContentKind[] = [
  "copy",
  "seo",
  "blog",
  "pinterest",
  "email",
  "social",
  "funnel",
  "other",
];
const KIND_LABEL: Record<ContentKind, string> = {
  copy: "Product copy",
  seo: "SEO",
  blog: "Blog",
  pinterest: "Pinterest",
  email: "Email",
  social: "Social",
  funnel: "Funnels",
  other: "Other",
};

function groupByKind(items: ContentItem[]): Map<ContentKind, ContentItem[]> {
  const m = new Map<ContentKind, ContentItem[]>();
  // Preserve insertion order within each kind (= the Builder's plan order
  // reversed by saveContent, then by createdAt desc — matches what users
  // see in the Library).
  for (const it of items) {
    const arr = m.get(it.kind) ?? [];
    arr.push(it);
    m.set(it.kind, arr);
  }
  // Sort each group by createdAt ascending so the workspace reads top-down
  // in the order the assets were originally generated.
  for (const arr of m.values()) {
    arr.sort((a, b) => a.createdAt - b.createdAt);
  }
  return m;
}
