// Deterministic markdown report generators. Pure functions over store data.
// These do NOT call AI — keep them fast, exportable, and predictable.
//
// AI-generated *insights* live in lib/insights.ts and are clearly labeled as
// such in the UI so the user can always tell raw data apart from AI analysis.

import type {
  Campaign,
  PerformanceSnapshot,
  Product,
} from "@/types";
import {
  byPlatform,
  byProduct,
  campaignTotals,
  fmtMoney,
  fmtPct,
  snapshotsInRange,
  topCampaigns,
  type CampaignTotals,
} from "./analytics";

function dateRange(days: number): { from: string; to: string } {
  const to = new Date();
  const from = new Date();
  from.setDate(from.getDate() - days);
  return {
    from: from.toISOString().slice(0, 10),
    to: to.toISOString().slice(0, 10),
  };
}

function totalsBlock(t: CampaignTotals): string {
  return [
    `- Impressions: **${t.impressions.toLocaleString()}**`,
    `- Clicks: **${t.clicks.toLocaleString()}**`,
    `- CTR: **${fmtPct(t.ctr)}**`,
    `- Sales: **${t.sales.toLocaleString()}**`,
    `- Conversion rate: **${fmtPct(t.conversionRate)}**`,
    `- Revenue: **${fmtMoney(t.revenue)}**`,
    `- Cost: **${fmtMoney(t.cost)}**`,
    t.roi !== null ? `- ROI: **${fmtPct(t.roi, 0)}**` : `- ROI: —`,
    t.cpc !== null ? `- Cost per click: **${fmtMoney(t.cpc)}**` : `- Cost per click: —`,
    t.costPerConversion !== null
      ? `- Cost per conversion: **${fmtMoney(t.costPerConversion)}**`
      : `- Cost per conversion: —`,
  ].join("\n");
}

export function campaignSummary(
  campaign: Campaign,
  snapshots: PerformanceSnapshot[],
  products: Product[]
): string {
  const t = campaignTotals(campaign.id, snapshots);
  const linkedProducts = products
    .filter((p) => campaign.productIds.includes(p.id))
    .map((p) => `- ${p.title}`)
    .join("\n");
  return `# Campaign summary — ${campaign.name}

**Platform:** ${campaign.platform}
**Goal:** ${campaign.goal}
**Status:** ${campaign.status}
**Start:** ${campaign.startDate}${campaign.endDate ? ` · **End:** ${campaign.endDate}` : ""}
**Budget:** ${fmtMoney(campaign.budget)}
**Tags:** ${campaign.tags.join(", ") || "—"}

## Linked products
${linkedProducts || "_None linked._"}

## Performance totals
${totalsBlock(t)}

## Notes
${campaign.notes || "_None._"}

## Audience notes
${campaign.audienceNotes || "_None._"}

## Lessons learned
${campaign.lessonsLearned || "_None recorded._"}

## Optimization ideas
${campaign.optimizationIdeas || "_None recorded._"}

_Generated by AI Copywriting OS on ${new Date().toISOString().slice(0, 10)}._
`;
}

function rollupReport(
  title: string,
  fromDate: string,
  toDate: string,
  campaigns: Campaign[],
  snapshots: PerformanceSnapshot[],
  products: Product[]
): string {
  const winSnaps = snapshotsInRange(snapshots, fromDate, toDate);
  const overall = (() => {
    const ids = new Set(winSnaps.map((s) => s.campaignId));
    const cmps = campaigns.filter((c) => ids.has(c.id));
    return {
      cmps,
      totals: campaigns
        .map((c) => campaignTotals(c.id, winSnaps))
        .reduce<CampaignTotals>((acc, t) => {
          acc.impressions += t.impressions;
          acc.clicks += t.clicks;
          acc.sales += t.sales;
          acc.revenue += t.revenue;
          acc.cost += t.cost;
          return acc;
        }, {
          impressions: 0,
          clicks: 0,
          saves: 0,
          shares: 0,
          comments: 0,
          emailOpens: 0,
          emailClicks: 0,
          websiteVisits: 0,
          productPageVisits: 0,
          sales: 0,
          revenue: 0,
          cost: 0,
          ctr: null,
          conversionRate: null,
          roi: null,
          cpc: null,
          costPerConversion: null,
        }),
    };
  })();
  // Compute derived ratios on the aggregate
  overall.totals.ctr =
    overall.totals.impressions > 0
      ? overall.totals.clicks / overall.totals.impressions
      : null;
  overall.totals.conversionRate =
    overall.totals.clicks > 0
      ? overall.totals.sales / overall.totals.clicks
      : null;
  overall.totals.roi =
    overall.totals.cost > 0
      ? (overall.totals.revenue - overall.totals.cost) / overall.totals.cost
      : null;
  overall.totals.cpc =
    overall.totals.clicks > 0 ? overall.totals.cost / overall.totals.clicks : null;
  overall.totals.costPerConversion =
    overall.totals.sales > 0 ? overall.totals.cost / overall.totals.sales : null;

  const top = topCampaigns(campaigns, winSnaps, "revenue", 5);
  const platforms = byPlatform(campaigns, winSnaps);
  const productsBd = byProduct(campaigns, winSnaps, products);

  return `# ${title}

**Range:** ${fromDate} → ${toDate}
**Campaigns with activity:** ${overall.cmps.length}

## Overall totals
${totalsBlock(overall.totals)}

## Top campaigns by revenue
${
  top.length === 0
    ? "_No campaigns with revenue in this window._"
    : top
        .map(
          (x, i) =>
            `${i + 1}. **${x.campaign.name}** — ${fmtMoney(x.totals.revenue)} revenue · ${x.totals.sales} sales · ${fmtPct(x.totals.ctr)} CTR`
        )
        .join("\n")
}

## Platform comparison
${
  platforms.length === 0
    ? "_No platform activity in this window._"
    : platforms
        .map(
          (p) =>
            `- **${p.platform}** — ${p.campaigns} campaigns · ${p.impressions.toLocaleString()} impressions · ${p.clicks.toLocaleString()} clicks · ${fmtMoney(p.revenue)} revenue`
        )
        .join("\n")
}

## Product performance
${
  productsBd.length === 0
    ? "_No product attribution in this window._"
    : productsBd
        .slice(0, 10)
        .map(
          (p) =>
            `- **${p.product}** — ${fmtMoney(p.revenue)} attributed revenue · ${Math.round(p.sales)} attributed sales`
        )
        .join("\n")
}

_Product attribution distributes a campaign's totals equally across all linked products._

_Generated by AI Copywriting OS on ${new Date().toISOString().slice(0, 10)}._
`;
}

export function weeklyReport(
  campaigns: Campaign[],
  snapshots: PerformanceSnapshot[],
  products: Product[]
): string {
  const { from, to } = dateRange(7);
  return rollupReport("Weekly campaign report", from, to, campaigns, snapshots, products);
}
export function monthlyReport(
  campaigns: Campaign[],
  snapshots: PerformanceSnapshot[],
  products: Product[]
): string {
  const { from, to } = dateRange(30);
  return rollupReport(
    "Monthly campaign report",
    from,
    to,
    campaigns,
    snapshots,
    products
  );
}
export function quarterlyReport(
  campaigns: Campaign[],
  snapshots: PerformanceSnapshot[],
  products: Product[]
): string {
  const { from, to } = dateRange(90);
  return rollupReport(
    "Quarterly campaign report",
    from,
    to,
    campaigns,
    snapshots,
    products
  );
}

export function productPerformanceReport(
  campaigns: Campaign[],
  snapshots: PerformanceSnapshot[],
  products: Product[]
): string {
  const rows = byProduct(campaigns, snapshots, products);
  return `# Product performance report

${
  rows.length === 0
    ? "_No campaign-attributed product performance yet._"
    : rows
        .map(
          (r) =>
            `## ${r.product}\n- Attributed revenue: **${fmtMoney(r.revenue)}**\n- Attributed sales: **${Math.round(r.sales)}**\n- Attributed clicks: **${Math.round(r.clicks)}**\n- Campaigns involved: **${r.campaigns.toFixed(1)}**`
        )
        .join("\n\n")
}

_Generated by AI Copywriting OS on ${new Date().toISOString().slice(0, 10)}._
`;
}

export function platformComparisonReport(
  campaigns: Campaign[],
  snapshots: PerformanceSnapshot[]
): string {
  const rows = byPlatform(campaigns, snapshots);
  return `# Platform comparison report

${
  rows.length === 0
    ? "_No platform activity yet._"
    : rows
        .map(
          (r) =>
            `## ${r.platform}\n- Campaigns: **${r.campaigns}**\n- Impressions: **${r.impressions.toLocaleString()}**\n- Clicks: **${r.clicks.toLocaleString()}**\n- Sales: **${r.sales.toLocaleString()}**\n- Revenue: **${fmtMoney(r.revenue)}**`
        )
        .join("\n\n")
}

_Generated by AI Copywriting OS on ${new Date().toISOString().slice(0, 10)}._
`;
}

export function topCampaignsReport(
  campaigns: Campaign[],
  snapshots: PerformanceSnapshot[]
): string {
  const top = topCampaigns(campaigns, snapshots, "revenue", 10);
  return `# Top-performing campaigns

${
  top.length === 0
    ? "_No campaigns with revenue yet._"
    : top
        .map(
          (x, i) =>
            `${i + 1}. **${x.campaign.name}** (${x.campaign.platform})\n   - Revenue: **${fmtMoney(x.totals.revenue)}** · Sales: ${x.totals.sales} · CTR: ${fmtPct(x.totals.ctr)} · ROI: ${fmtPct(x.totals.roi, 0)}`
        )
        .join("\n\n")
}

_Generated by AI Copywriting OS on ${new Date().toISOString().slice(0, 10)}._
`;
}
